### ISSUE TITLE
Broken link in MyAssetManagerInterface.py

### ISSUE THREAD

**Issue by brycegbrazen** [OpenAssetIO/Template-OpenAssetIO-Manager-Python#25]
https://github.com/OpenAssetIO/Template-OpenAssetIO-Manager-Python/blob/main/plugin/my_asset_manager/MyAssetManagerInterface.py#L35

This link at this line seems to be a link I should be able to open? Assuming this is a bug?

**Comment by feltech** [comment]
Well spotted, thanks!  The link should be

https://openassetio.github.io/OpenAssetIO/classopenassetio_1_1v1_1_1manager_api_1_1_manager_interface.html

For posterity, the link is currently https://openassetio.github.io/OpenAssetIO/classopenassetio_1_1manager_api_1_1_manager_interface_1_1_manager_interface.html - note the missing `v1_1_1`. 

This looks like a link from before the `ManagerInterface` class was migrated to C++.
