### ISSUE TITLE
Update template to OpenAssetIO v1.0.0-alpha.14

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/Template-OpenAssetIO-Manager-Python#4]
Various breakages due to

- https://github.com/OpenAssetIO/OpenAssetIO/issues/1048
- https://github.com/OpenAssetIO/OpenAssetIO/issues/1054

Remember to check docs.

**Comment by feltech** [comment]
An interesting aside whilst working on this

With pip 21.2.4, attempting to do an editable/develop install fails

```shell
$ pip install -e .
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/dave/workspace/cloud/assetapi/Template-OpenAssetIO-Manager-Python
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```

but with (latest) pip 23.2.1 (after doing a `pip install --upgrade pip`) it succeeds.
