### ISSUE TITLE
Update to latest `openassetio` `v1.0.0b1`

### ISSUE THREAD

**Issue by foundrytom** [OpenAssetIO/Template-OpenAssetIO-Manager-Python#8]
## What

Update template to refactor best pracrices in v1.0.0b

**Comment by elliotcmorris** [comment]
We overlap support for both beta 1 and alpha 14 in the template to maintain compatibility with certain existing hosts. If and when these update, (or if just enough time passes...) remove the overlap.

**Comment by elliotcmorris** [comment]
Removed this when adding entity traits, because it was too much of a burden to maintain parallel versions.
